### ISSUE TITLE
Database connector

### ISSUE THREAD

**Issue by matteocrippa** [elliottminns/blackfish#13]
Hi, I really like your work because I'm a fan of Express.js and I think swift would be very interesting switch.

I think it would be very interesting to add some DB connectors (eg. MySQL/MariaDB and MongoDB) as default one in order to provide more appeal to blackfish project. What do you think?

**Comment by elliottminns** [comment]
I like this idea. I'm unsure whether it should be default or another module that people can attach, similar to what I've currently got with [blackfish-stencil](https://github.com/elliottminns/blackfish-stencil)

I've been looking into [SwiftMongoDB](https://github.com/nicksweet/SwiftMongoDB) as the first database driver to use within blackfish.

**Comment by matteocrippa** [comment]
Prob the best way is a module like it happens in express.js.

It would be even cooler to have something like [Sequelize](http://docs.sequelizejs.com/en/latest/) or [CaminteJS](http://www.camintejs.com) as ORM, but in the meanwhile if you are interested in swift database libs supporting linux you can have a look here: https://github.com/matteocrippa/awesome-swift#data-management

**Comment by elliottminns** [comment]
I do think this is quite necessary, however it looks like it may be a separate project rather than in the core web framework code. I will have a look at those links though and see which one looks like it has a really clean interface. 

Are there any other ORM's you're particularly fond of so I can check them out?

**Comment by matteocrippa** [comment]
On my past experience with express.js I usually managed to use that ORM or directly the library for mongodb or couchdb.

Another interesting approach is the one provided by Loopback.io that is build on top of express with [https://docs.strongloop.com/display/public/LB/Connecting+models+to+data+sources](dedicated modules for storage), even for filesystem storage too.

**Comment by elliottminns** [comment]
I've been working on one today that uses reflection as an ODM, based on Mongoose. I think it's a nice solution (Although not 100% awesome due to current limitations with swift). Currently the setup looks like this:

``` swift

class Cat: Model {

    var identifier: String?
    var name: String
    var age: Int
    var claws: Double?

    init(name: String, age: Int) {
        self.name = name
        self.age = age
    }

    required init?(serialized: [String: DataType]) {
        self.identifier = serialized["identifier"] as? String
        self.name = serialized["name"] as! String
        self.age = serialized["age"] as! Int
        self.claws = serialized["claws"] as? Double
    }
}

let kitty = Cat(name: "Stephen", age: 10) 

kitty.save() { error in 
    if error == nil {
        print("Meow")
    }
}

```

The repository is here - [Orca](https://github.com/elliottminns/Orca)

Once I've got the final details added in, I'll add a MongoDB or SQLite Driver to it. It currently just stores in memory.

**Comment by Keloran** [comment]
I'm currently trying to create a small package to allow SQLite interactions, and a starter (rubbish) ORM

**Comment by matteocrippa** [comment]
Have you ever heard about [GraphQL](http://graphql.org/docs/getting-started/)?
I noticed a project of a porting for [swift](https://github.com/justinmakaila/Swift-GraphQL) that needs to be improved a little (at least add support for Alamofire in a better way and test under 2.2)

**Comment by matteocrippa** [comment]
[Fluent](https://github.com/tannernelson/fluent) seems pretty interesting

**Comment by elliottminns** [comment]
Yeah, I had a look at fluent, but it appears to be blocking I/O which wouldn't work with blackfish. I should have something released in the next couple of days.

**Comment by matteocrippa** [comment]
Cool, if I have a little spare time I'll try to give a little hep, in the meanwhile I'm planning to make a total conversion of torii.js to blackfish, it would be an interesting baas opensource

**Comment by elliottminns** [comment]
Awesome, I've not got any experience with torii.js so I'll check it out today.

I've pushed the first stable version of [Orca](https://github.com/elliottminns/orca) today. 

It currently only supports an in-memory store as default. I'm adding a module that will support SQLite and hopefully Mongodb, provided that I can get the `module.modulemap` to build (I'm currently experiencing issues with the mongo-c driver).

**Comment by matteocrippa** [comment]
torii.js is pretty unknown, it is an open-source baas, but recently when Parse dropped support it is striking back a little more.

Another solution is to check if [Realm](https://realm.io/docs/swift/latest/) is planning any support for swift 2.2+

**Comment by rtalwar26** [comment]
you could try [ DataStoreKit](https://github.com/poolmyride/DataStoreKit) . Pure Swift library supporting inmemory,coredata,REST stores. May be this can be of some use.

**Comment by elliottminns** [comment]
I've started working on a MongoDB connector for Orca today, the only caveat is that you have to build by passing in compiler flags as highlighted with [this pull request](https://github.com/apple/swift-package-manager/pull/107) on Swift package manager.

`swift build -Xcc -I/usr/lib/bson/`

I think it's fine for a current solution, and when the swift package manager better handles Include paths, it will be more elegant.

**Comment by katopz** [comment]
MongoDB :+1:

**Comment by elliottminns** [comment]
The [Orca MongoDB](https://github.com/elliottminns/orca-mongodb) driver has now been added.

It's very experimental on Linux as I need to finalise testing but is working correctly on OS X.

It also has quite a limited functionality, but this will improve in time. 

Anyone wishing to use it will need to follow the instructions for installing the Mongo C driver on their respective platform. I'll look at embedding a library for each platform in future as it'll be easier for most people, or wait until the Swift Package Manager has better support for C libraries. 

I'll close this issue once I verify it's working on Ubuntu.

**Comment by matteocrippa** [comment]
It would be interesting to create a docker container for swift2.2 in order to easily setup blackfish + orca so you can guarantee the right compatibility with ubuntu

**Comment by elliottminns** [comment]
I agree. I think that's going to be my next step. It's almost at the stage that I can use it internally for a project that needs doing which will involve using Docker for deployment.

**Comment by matteocrippa** [comment]
I haven't test it yet, but it should work https://github.com/boostcode/docker-swift-git

**Comment by elliottminns** [comment]
I've managed to get the Linux version to work correctly for MongoDB. 

I'm going to check it in the morning when i'm more refreshed to check it's all okay before closing this off.

**Comment by elliottminns** [comment]
Just been testing this today on my internal product. It all works nicely now with MongoDB. I had to push a quick fix but otherwise its all okay :).

[Orca](https://github.com/elliottminns/orca)
[OrcaMongoDB](https://github.com/elliottminns/orca-mongodb)

Closing this issue
