### ISSUE TITLE
Mac OS X / Cocoa Pods support ?

### ISSUE THREAD

**Issue by TheAbstractDev** [elliottminns/blackfish#14]

**Comment by matteocrippa** [comment]
@TheAbstractDev as far as I know osx is supported, but you have to download the Swift 2.2-dev version in order to use the package builder of swift.

**Comment by TheAbstractDev** [comment]
Okay, thanks you @matteocrippa. Will blackfish supports cocoapods ?

**Comment by elliottminns** [comment]
It will support cocoapods. Currently however, it uses swift 2.2, so I want to wait until that is released before releasing it on Cocoapods.
