### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by ericgiannini** [elliottminns/blackfish#17]
What would we need to do to incorporate support for HTTPS?

**Comment by elliottminns** [comment]
That's a good question. 

I think some hosting sites and virtual servers, like Heroku, may provide this already through their proxies. 

However, I don't believe the current functionality can support HTTPS manually, this is something that I'll add to the backlog of things to do. I'll take a look at this once I've got the mongodb database driver working.

**Comment by ericgiannini** [comment]
Is there a way to contact you via email?

**Comment by elliottminns** [comment]
elliott.minns@me.com

**Comment by matteocrippa** [comment]
I agree with Elliott, if user will use it in production they would use nginx that provides proxy with https support.

Express.js supports https, but I'd to say that I have never used it and I always put an nginx proxy never exposing it directly.

**Comment by elliottminns** [comment]
Closing this issue as I believe it's currently out of scope for Blackfish to handle HTTPS manually.

**Comment by abiaad** [comment]
Do you have a nginx file exemple to serve a Blackfish app through https ?
I began to wrote :

```
server {
        listen 443;
        server_name mydomain.com;

        root projects/blackfish_app;
        index index.html index.htm;

        ssl on;
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
}
```

I'm working on it because not working at this time (working with default nginx config on a www folder and index.html)

**Comment by elliottminns** [comment]
This is something I'll have a look into today. Thanks for raising this issue.

**Comment by abiaad** [comment]
Cool ! 👍
