### ISSUE TITLE
Document specific Dev Snapshot used for testing.

### ISSUE THREAD

**Issue by rpanchal** [elliottminns/blackfish#20]
It would help if you could document which specific Swift Dev-Snapshot you are using to test this as of right now.

**Comment by elliottminns** [comment]
Duly noted, I'll add that tonight.

**Comment by elliottminns** [comment]
Done :)

**Comment by rpanchal** [comment]
Are you only testing with OS X snapshots? or Ubuntu snapshots? And if you are testing ubuntu snapshots which one?

Just asking so you don't have to field these questions from everyone.

**Comment by elliottminns** [comment]
Ubuntu Trusty 14.04 and OS X

I currently have an internal project using blackfish as its web server which is developed on OS X and running on Ubuntu. 

I'll add these details to the README

**Comment by rpanchal** [comment]
Awesome. Thanks.
