### ISSUE TITLE
A small typo on README.md

### ISSUE THREAD

**Issue by gwangpa** [elliottminns/blackfish#22]
Hi, I just found your project and it's interesting me. I'm expecting Swift will be used beyond iOS/OSX dev.

I read README.md first and got a little bit strange part.

In Controller section,

You define `MyController` and in main.swift you added controller this 

``` swift
app.use(path: "/test", controller: Test())
```

I can't test your example since I'm having a problem to install Swift 2.2, but in my programming sense it's supposed to be

``` Swift
app.use(path: "/test", controller: MyController())
```

rather `Test()` I think?

Could you check it out and if my guess is right I would be happy to make change.

Thanks,

**Comment by elliottminns** [comment]
You're correct, sloppy pasting by myself there :).
