### ISSUE TITLE
Example on extracting data from post or put

### ISSUE THREAD

**Issue by glessard** [elliottminns/blackfish#23]
I'm unclear on how to extract data from a post or put using this library; I seem to only find empty dictionaries. Could you add an example?
Thanks!

**Comment by elliottminns** [comment]
No problem, I'll add one to the README and this issue shortly.

**Comment by elliottminns** [comment]
Here is my example set up

 `main.swift`

``` swift
let app = Blackfish()

app.get("/") { (request, response) in
    response.render("index.html")
}

app.put("/") { (request, response) in
    print(request.data)
    response.redirect("/")
}
app.post("/") { (request, response) in
    print(request.data)
    response.redirect("/")
}

app.listen(port: 3000) { error in
    if error == nil {
        print("App listening on port 3000")
    } else {
        print("Error")
    }
}
```

Then, using curl to post data:

`curl --data "test=2&name=foo" http://127.0.0.1:3000`

I get the following output:

```
App listening on port 3000
["test": "2", "name": "foo"]
```

Using PUT gives me the same output

`curl -X PUT --data "test=2&name=foo" http://127.0.0.1:3000`

`["test": "2", "name": "foo"]`

**Comment by elliottminns** [comment]
Added to the README.md as well, let me know how it goes and if all is okay, we'll close the issue :)

**Comment by glessard** [comment]
That was useful, thanks. I thought NSURLSession did more than it does for uploads; that's what I get for trying two new things at once.

**Comment by elliottminns** [comment]
No problem, if you need to do file uploads make sure you use the `Multiparser` middleware that comes built in: [Multipart](https://github.com/elliottminns/blackfish#multipart)
