### ISSUE TITLE
Request Library - Proposal

### ISSUE THREAD

**Issue by elliottminns** [elliottminns/blackfish#24]
Most modern API's required the ability to send out HTTP requests to other services.

Currently there aren't any other HTTP servers providing this, and for Blackfish to be a number one Web Server, it should have this functionality.

My proposal is that seeming though Echo is what is powering the Event Loop behind Blackfish, and given  it's asynchronous nature, the Request library should also be powered by Echo and it's own repository. This means that it'll be reusable across other packages and will also be non-blocking. 

My thought process is to use [libcurl](https://curl.haxx.se/libcurl/c/) as the main driver and implement a wrapper in swift to open up this process. The best JSON parsing library I have currently found is [Swift-PureJsonSerializer](https://github.com/gfx/Swift-PureJsonSerializer) and I think would add a nice addition to the Requesting Library.

**Comment by matteocrippa** [comment]
Yep external calls would be awesome for eg. sending mail via third party service (prob it would be interesting even to port even something like [Nodemailer](https://nodemailer.com) and other libs)

**Comment by elliottminns** [comment]
I agree, hopefully with a core networking library, other modules will start to form from it. I'm torn whether to use an already established library (Such as libcurl) or just write it from scratch using posix / darwin sockets.

**Comment by matteocrippa** [comment]
Haven't checked yet, isn't there any Alamofire brach that works with Swift linux yet?

**Comment by elliottminns** [comment]
Not at the moment, Alamofire relies on NSURLSession which hasn't yet been implemented for Swift Linux. 

I intend it to be the next task as I feel it's key requirement for any web server (I'm currently needing it in my internal work)

**Comment by czechboy0** [comment]
Hey @elliottminns, if you want a pure Swift, well tested JSON serialization lib, I wrote https://github.com/czechboy0/Jay
It's used by Vapor (instead of Swift-PureJsonSerializer which isn't as robust to crazy unicode like Jay is). Feel free to use it here :)

**Comment by elliottminns** [comment]
Available via [Narwhal](https://github.com/elliottminns/narwhal)
