### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by elliottminns** [elliottminns/blackfish#3]
Be able to add middleware that can intercept any handlers before passing it on to its next handler

See http://expressjs.com/en/guide/writing-middleware.html for example

**Comment by gregpardo** [comment]
Definitely essential feature. I would propose that it should allow a default middleware stack and a customizable per route middleware stack override. This is one thing I always found frustrating about express. I would often write my own middleware that selectively applied others depending on the route.

**Comment by elliottminns** [comment]
I like your thoughts, I've currently got it set up similar to how express is working on the `feature/middleware` branch. Any proposals on how you think the interface should look for overriding the default stack on a particular route?

**Comment by gregpardo** [comment]
What about just something like this 

```
app.defaultMiddlewares = [SomeMiddleWare(), SomeOtherMiddleWare(config)]

let alternateMiddleware = [AltMiddleWare()]

// Uses default
app.get("/") { request, response in
    response.send(text: "Hello World!")
}

// Uses alternate
app.get("/", alternateMiddleware) { request, response in
    response.send(text: "Hello World!")
}
```

**Comment by elliottminns** [comment]
I like it, I'll create another issue to add this in to the current model
