### ISSUE TITLE
JSON not working

### ISSUE THREAD

**Issue by svanimpe** [elliottminns/blackfish#33]
The following

`response.send(json: ["message": "Hello World"])`

does not compile, with the following error:

`contextual type AnyObject cannot be used with dictionary literal`.

This is using the February 8 build on Ubuntu.

**Comment by elliottminns** [comment]
I shall look into this, I think it's an issue with AnyObject and Any on Linux. I'll get a fix up shortly.

**Comment by elliottminns** [comment]
I've added a fix #34 . Just waiting for the CI to succeed and then I'll merge it in under tag 1.0.11

**Comment by elliottminns** [comment]
Fixed :)
