### ISSUE TITLE
JSON input

### ISSUE THREAD

**Issue by svanimpe** [elliottminns/blackfish#38]
It is unclear to me whether Blackfish supports JSON input or not.
I've tried sending a POST request with JSON in the body, but cannot find any properties on `request` to read it. There is a `body` property, but that's internal and simply a byte array.

**Comment by elliottminns** [comment]
Blackfish currently doesn't support JSON input. It's something I'm going to work on this weekend writing a piece of middleware for it. 

I'll keep you updated. Hopefully I'll have it written shortly.

**Comment by svanimpe** [comment]
Thanks. I'll give it a try when it's ready.

**Comment by elliottminns** [comment]
I have a solution on branch `feature/json-request` with tag `0.1.13` up and running. 

I'm not sure if it's exhaustive, there's probably some cases I haven't accounted for. 

From my testing it works for:

```
Int

Double

Bool // true || false

Array

Object

String
```

I'm going to test it's running correctly on Linux in the mean time, however feel free to give it a go for OS X. 

I'll write up some documentation for it when I get a chance today.

**Comment by elliottminns** [comment]
Working on Linux, I'll merge into master. 

Let me know if it's all okay and we'll close off this issue :)

Thanks for raising this, it's an important feature to have.

**Comment by svanimpe** [comment]
So far everything seems to work using `request.data`. I'll let you know via this issue if I run into more JSON issues. Thanks for fixing this so fast!

**Comment by svanimpe** [comment]
This is broken again. Even though I send a JSON object in the body of the request, `request.data` is empty.

**Comment by elliottminns** [comment]
Thanks for raising this. Just had a look and it was something missing in the architecture change. It now works with version `0.4.2`

I need to get some regression tests added in when I get a chance. :)

**Comment by svanimpe** [comment]
I still have the same problem with `0.4.2`?

**Comment by elliottminns** [comment]
Hmmm, OS X or Ubuntu?

Here is the output of this for me:

```
app.post("/") { request, response in
    print(request.data)

    for (key, value) in request.data {
        print("\(key): \(value)")
    }
    response.send(json: request.data)
}
```

```
$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "{'json':{'data':'here'}}" http://127.0.0.1:3000

HTTP/1.1 200 OK
Server: Blackfish 0.1.3
Content-Type: application/json
Content-Length: 39
Connection: keep-alive

{"json":{"data":"here"},"startTime":""}

```

**Comment by svanimpe** [comment]
Ubuntu 15.10 with the March 1 snapshot

**Comment by elliottminns** [comment]
I'll give it a go shortly and see what happens.

**Comment by elliottminns** [comment]
Have you got a clean distribution? The tag got pushed before the commit as I hadn't pulled so it may have caused an issue

**Comment by elliottminns** [comment]
Just tested it on Ubuntu 14.10, it all works fine my side. What is the JSON request you're sending?
