### ISSUE TITLE
500 Internal Server Error (InvalidPath) on seemingly trivial routes

### ISSUE THREAD

**Issue by svanimpe** [elliottminns/blackfish#39]
My app is set up as follows:

```
let app = Blackfish()
let model = Model()

app.use(renderer: StencilRenderer(), ext: ".stencil")

app.get("/") { request, response in
  response.render("index.stencil")
}
app.get("/students.html") { request, response in
  response.render("students.stencil", data: ["students": model.students])
}

app.use(path: "/api/students", controller: StudentController(model: model))
app.use(path: "/api/courses", controller: CourseController(model: model))

app.listen(port: 3000) { error in
  print(error ?? "BlackFishTest listening on port 3000")
}
```

The error is related to the paths `/` and `/students.html`. The paths starting with `api` still work as before. Files `index.stencil` and `students.stencil` are in the `Resources` folder. What's wrong here?

I'm using the February 8 build on Ubuntu.

**Comment by elliottminns** [comment]
Can I get you to do `swift build --clean=dist` and then `swift build`

I pushed a late night fix for a break with the way middleware and routes were handled which might fix this issue. 

If that doesn't work, I'll investigate. 

The only other thing I can think of is that there's an error with loading the stencil files.

**Comment by svanimpe** [comment]
That didn't work.

**Comment by elliottminns** [comment]
Does returning JSON instead of `.stencil` work or do you still get a server error?

**Comment by svanimpe** [comment]
Returning JSON works.

**Comment by elliottminns** [comment]
Could I get a copy of your `index.stencil`?

**Comment by svanimpe** [comment]
index.stencil:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Welcome</title>
</head>
<body>
    <ul>
        <li><a href="students.html">Students</a></li>
        <li><a href="courses.html">Courses</a></li>
    </ul>
</body>
</html>
```

students.stencil:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Students</title>
</head>
<body>
    <ul>
    {% for student in students %}
        <li>{{ student.id }}: {{ student.name }}</li>
    {% endfor %}
    </ul>
</body>
</html>
```

**Comment by elliottminns** [comment]
I don't seem to be having the issue my side with the `index.stencil`. 

Are the stencil files inside of `Resources/` or are they nested in another directory inside of it?

e.g.

```
Resources/Views/index.stencil
```

If the latter is the case, then you'll need to do:

``` swift
response.render("Views/index.stencil")
```

Is there anyway I can clone your project to give it a go? That way I can figure out what is happening internally.

**Comment by svanimpe** [comment]
https://github.com/svanimpe/blackfish-example

**Comment by elliottminns** [comment]
Running with your `index.stencil` example, everything appears to work my side on Ubuntu 14.04

On the `student.stencil` it renders but it seems to have a problem with the data. If I do this

``` swift
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Students</title>
</head>
<body>
    <p> {{students}}</p>
    <ul>
    {% for student in students %}
        <li>{{ student.id }}: {{ student.name }}</li>
    {% endfor %}
    </ul>
</body>
</html>
```

I get a web page which renders:

```
[BlackFishTest.Student, BlackFishTest.Student]
```

I think it's a problem with Stencil handling the `Any` object. I'll update my renderer this weekend to handle the `Any` object type. 

Looking at the Stencil renderer I can see that there is an issue related to this https://github.com/kylef/Stencil/issues/51

**Comment by elliottminns** [comment]
Is there any error's that are produced which would explain why your index page isn't loading?

**Comment by svanimpe** [comment]
This appears to be have been an issue with CLion (the IDE I'm using on Linux). If I run the app from the command line, from its root folder, the index stencil works. I think CLion ran the app from the .build/debug folder, in which case the stencils weren't found. Setting the working directory to the project root in the build settings fixed this.

**Comment by elliottminns** [comment]
I'll post a workaround shortly on how to process the data using Stencil. It's not ideal but it'll get you the results you want at the moment.

**Comment by kylef** [comment]
Just want to mention, I've fixed https://github.com/kylef/Stencil/issues/51 in Stencil 0.5.3. Please let me know if there are any released problems.

-Kyle

**Comment by elliottminns** [comment]
Oh that's awesome, thanks @kylef 

I'll give that a test later and feedback
