### ISSUE TITLE
Is blackfish using non-blocking IO

### ISSUE THREAD

**Issue by guidomb** [elliottminns/blackfish#42]
Hey cool project! I took a quick look at the source code and I see that you are using `recv` to read data from the socket. As far as I know that function blocks if there is no data to be read. Did I get this right?  Are you planning to add non-blocking IO in the near feature?

**Comment by elliottminns** [comment]
Thank you :)

You're correct `recv` does block if there is no data. 

The project currently supports non-blocking I/O using an event loop. An event loop is created using another [module](https://github.com/elliottminns/echo) I have. I/O is then handled on separate queues with the handlers being passed back to the event queue/main thread. 

I do intend to replace `recv` with something non blocking in the future. Currently, my main focus is on creating core functionality and clean API's which will be followed by under the hood tweaking to adjust things like this.

I'm also very open for contributions to help this process as well :)

**Comment by guidomb** [comment]
I being thinking of doing something similar to this. Since you started this project I think it will make much more sense to contribute to this instead of a creating a new one. Have you consider using libuv for IO?. It is what powers Nodejs. There is similar work already been done [here](https://github.com/CaramelForSwift/Caramel) I think that by using libuv you won't be bound by the amount of thread in the IO and the server will be able to handle more connections.

**Comment by elliottminns** [comment]
Contribution would be awesome. 

I hadn't considered it before, but it makes a lot of sense to use it in my opinion. Node.js has proven its scalability, so Blackfish being powered by the same core makes perfect sense to increase it's performance. 

I'll have a look at Caramel in more detail. 

What proposal do you think would be better suited:

To use an existing swift wrapper around libuv i.e Caramel ?

or

Create a new one which has been built for purpose?

As I'm going to focus mainly on the public interface and core features, I'd be more than happy to let someone take ownership of the core libuv side of things. It could even work in the sense of how Express.js wraps around Node.js.

**Comment by guidomb** [comment]
I think the best approach for this case would be to call libuv directly. I'll be more than happy to add that contribution once I finished my backlog on my own OSS projects!

**Comment by elliottminns** [comment]
I agree. I think being built to purpose is important. 

I'll add libuv to the roadmap for 1.0

I've also seen a proposal in the Swift Package Manager mailing list that intends to support C projects as packages. This could prove useful for integration within Blackfish.

**Comment by elliottminns** [comment]
libuv is now added in with version 0.4.0, it requires having it installed on your system however. Read via the Wiki or README.md

**Comment by guidomb** [comment]
Ohh nice!!!

**Comment by elliottminns** [comment]
It's only got support for networking atm but I'll extend it to the filesystem this week :)
