### ISSUE TITLE
typealias problem

### ISSUE THREAD

**Issue by nonameplum** [elliottminns/blackfish#48]
Hi,

Because of used names in framework there is problem when we have to deal with ambiguous names. In my case where I want to use SwiftHTTP and Blackfish where in both is class `Response`.

But we can't use `Blackfish.Response` because there is declared class in Blackfish framework called 'Blackfish' so swift is complain that: `'Response' is not a member type of 'Blackfish'`

**Comment by elliottminns** [comment]
Hi @nonameplum, 

Could you give me an example so that I can replicate this issue? 

I'll try and get a workaround / fix shortly.

**Comment by nonameplum** [comment]
I created fork of your repo and renamed `Blackfish` class in `Application.swift` file to `BlackfishApp` then I can write code like here:
https://github.com/nonameplum/blackfish-github-badges/blob/master/Sources/IndexController.swift

I'm using there `.Package(url: "https://github.com/daltoniam/SwiftHTTP.git", versions: Version(1,0,0)..<Version(2,0,0))`

If you try use this code with your repo then you will see errors.

**Comment by elliottminns** [comment]
Closed with #50
