### ISSUE TITLE
Problem with unowned request

### ISSUE THREAD

**Issue by nonameplum** [elliottminns/blackfish#49]
With this method controller
https://github.com/nonameplum/blackfish-github-badges/blob/master/Sources/IndexController.swift#L16

I'm getting `SIGABRT` for `response.request` in line https://github.com/elliottminns/blackfish/blob/master/Sources/SocketServer.swift#L114

I forked you repo and changed `unowned let` to `weak var` to resolve my problem but I didn't fully catch why this happen.

**Comment by elliottminns** [comment]
Thanks for raising this. 

I'd be happy to have a pull request with your fixes in to update this issue. I'm assuming the `request` object is being deallocated and the `unowned` is then pointing to junk memory. Changing it to a `weak var` basically allows the request to be `nil` as opposed to garbage. I need to understand more what is causing this and whether or not it's correct to give the `Response` object a strong ownership.

**Comment by elliottminns** [comment]
Closed with #50
