### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [elliottminns/blackfish#63]
Below the title please add badges this help a lot. 

If your component is compatible: 
- with Carthage add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-brightgreen.svg)](https://github.com/Carthage/Carthage)
- with SwiftPM add [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager)
- with CocoaPods add pod version ![Pod Version](https://img.shields.io/badge/Pod-X.X.X-blue.svg)

Indicated:
- the Swift version ![Swift Version](https://img.shields.io/badge/Swift-3.0-orange.svg)
- Platforms supported ![Plaforms](https://img.shields.io/badge/Platforms-Linux%20%7C%20macOS%20%7C%20iOS%20%7C%20WatichOS%20%7C%20tvOS-lightgrey.svg)
- License ![License MIT](https://img.shields.io/badge/License-MIT-lightgrey.svg)

**Comment by elliottminns** [comment]
Thanks buddy, will add these in.
