### ISSUE TITLE
about work request module

### ISSUE THREAD

**Issue by iDevPro** [elliottminns/blackfish#66]
```
import Blackfire

let app = Flame(type: .concurrent)

app.get("/data") { (request, response) in
    print("query: \(request.query) ")
    print("params: \(request.params) ")
    print("path: \(request.path) ")
    print("body: \(request.body) ")
    response.send(html: "SOME")
}

app.start(port: 3000) { (result) in
    switch result {
    case .success:
        print("Server started on port 3000")
    case .failure(let error):
        print("Server failed with error: \(error)")
    }
}
```
1)
http://localhost:3000/data?param=res 
=>
query: [:] 
params: [:] 
path: /data 
body:  
query: [:] 
params: [:] 
path: /data 
body:  

2)
http://localhost:3000/data/param=res
=>
query: [:] 
params: [:] 
path: /data/param=res 
body:  

3)
http://localhost:3000/data/?param=res
=>
query: [:] 
params: [:] 
path: /data/ 
body: 

How I can pass params ?)

**Comment by iDevPro** [comment]
Hmmm, HTTPRequest fire two times at once :)

<img width="1512" alt="2017-01-25 22 48 37" src="https://cloud.githubusercontent.com/assets/1888230/22306490/877ce658-e350-11e6-996e-4ae200f1f026.png">
<img width="1512" alt="2017-01-25 22 48 52" src="https://cloud.githubusercontent.com/assets/1888230/22306491/877fb32e-e350-11e6-9eeb-248a6476d8c5.png">

**Comment by elliottminns** [comment]
There's a conversion that goes on two recreate the HTTPRequest as a standard Request. This'll be changed. I'll add in query params today 👍

**Comment by elliottminns** [comment]
Try it with 0.1.2
